# Generated by Django 5.2.8 on 2026-03-12 18:22

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaousuario_mostrar_feed_algoritmico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pergunta_secreta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='resposta_secreta',
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id_code', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_codes',
            },
        ),
    ]
