# Generated by Django 5.2.8 on 2026-03-19 22:07

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_pergunta_secreta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemdireta',
            options={'ordering': ['-data_envio']},
        ),
        migrations.AddField(
            model_name='mensagemdireta',
            name='publicacao_compartilhada',
            field=models.ForeignKey(blank=True, db_column='id_publicacao_compartilhada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartilhamentos_chat', to='core.publicacao'),
        ),
        migrations.AddField(
            model_name='mensagemdireta',
            name='tipo_mensagem',
            field=models.CharField(choices=[('text', 'Texto'), ('media', 'Mídia'), ('post', 'Publicação')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagemdireta',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id_conversa', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario_a', models.ForeignKey(db_column='id_usuario_a', on_delete=django.db.models.deletion.CASCADE, related_name='conversas_a', to=settings.AUTH_USER_MODEL)),
                ('usuario_b', models.ForeignKey(db_column='id_usuario_b', on_delete=django.db.models.deletion.CASCADE, related_name='conversas_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversas',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.AddField(
            model_name='mensagemdireta',
            name='conversa',
            field=models.ForeignKey(blank=True, db_column='id_conversa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.conversa'),
        ),
        migrations.CreateModel(
            name='UploadChat',
            fields=[
                ('id_upload', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='chat_media/')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='chat_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploads_chat',
            },
        ),
        migrations.AddField(
            model_name='mensagemdireta',
            name='upload',
            field=models.ForeignKey(blank=True, db_column='id_upload', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uploadchat'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['-data_atualizacao'], name='idx_conversa_updated'),
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.CheckConstraint(condition=models.Q(('usuario_a__lt', models.F('usuario_b'))), name='conversa_usuario_a_lt_b'),
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(fields=('usuario_a', 'usuario_b'), name='conversa_unica_1_para_1'),
        ),
    ]
