# Generated by Django 6.0 on 2026-04-03 19:57

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dm_v2_populate_conversas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceite_termos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ModeracaoConteudo',
            fields=[
                ('id_moderacao', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tipo_conteudo', models.CharField(choices=[('publicacao', 'Publicação'), ('comentario', 'Comentário'), ('usuario', 'Usuário'), ('mensagem', 'Mensagem Direta')], max_length=20)),
                ('id_conteudo', models.CharField(max_length=36)),
                ('acao', models.CharField(choices=[('remocao', 'Conteúdo Removido'), ('restauracao', 'Conteúdo Restaurado'), ('suspensao', 'Usuário Suspenso'), ('banimento', 'Usuário Banido'), ('advertencia', 'Advertência Emitida'), ('sem_acao', 'Analisado — Sem Ação Necessária')], max_length=20)),
                ('conteudo_snapshot', models.TextField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, default='')),
                ('data_acao', models.DateTimeField(default=django.utils.timezone.now)),
                ('retencao_minima_ate', models.DateField(blank=True, null=True)),
                ('denuncia_origem', models.ForeignKey(blank=True, db_column='id_denuncia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderacoes', to='core.denuncia')),
                ('moderador', models.ForeignKey(blank=True, db_column='id_moderador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderacoes_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_afetado', models.ForeignKey(blank=True, db_column='id_usuario_afetado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderacoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderacao_conteudo',
                'ordering': ['-data_acao'],
            },
        ),
    ]
