# Generated by Django 6.0 on 2026-05-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configuracaousuario_interesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='is_efemero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='interesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
