# Generated by Django 6.0 on 2026-05-01 00:11
#
# Reescrita para usar SeparateDatabaseAndState:
# O servidor de produção já possui as colunas 'expira_em' e 'is_efemero'
# na tabela 'publicacoes'. Usar SeparateDatabaseAndState atualiza o
# histórico de migrações do Django sem tentar recriar as colunas,
# evitando o erro: (1060, "Duplicate column name").

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configuracaousuario_interesses'),
    ]

    operations = [
        # SeparateDatabaseAndState separa o que o Django "sabe" do que
        # ele realmente executa no banco.
        # - state_operations: Django registra os campos no seu estado interno.
        # - database_operations: vazio — nenhum SQL é executado.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='publicacao',
                    name='expira_em',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='publicacao',
                    name='is_efemero',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='configuracaousuario',
                    name='interesses',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
            database_operations=[],
        ),
    ]
