# Generated by Django 6.0 on 2026-05-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_publicacao_expira_em_publicacao_is_efemero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='expira_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='is_efemero',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='publicacao',
            index=models.Index(fields=['is_efemero', 'expira_em'], name='idx_efemero_expira'),
        ),
    ]
